### ISSUE TITLE
callbak开放出来

### ISSUE THREAD

**Issue by MisterChing** [HDT3213/delayqueue#11]
1.希望 callback处理函数增加  WithCallback 开放出来
2.希望能增加队列阻塞监控

感谢~

**Comment by HDT3213** [comment]
抱歉，没看到这个 issue

队列阻塞这个我看看整个 opentelemetry 进去。
请问暴露 callback 是为了做什么呢

**Comment by ggdream** [comment]
@HDT3213 你好，我也认为考虑暴露callback，并且单独抽出生产者和消费者。我的理由是目前设计没有很好的解耦，想实现业务里投递Job消费的场景

**Comment by HDT3213** [comment]
@ggdream  生产者已经独立出来了。 [分开部署生产者和消费者](https://github.com/HDT3213/delayqueue/blob/master/README_CN.md#%E5%88%86%E5%BC%80%E9%83%A8%E7%BD%B2%E7%94%9F%E4%BA%A7%E8%80%85%E5%92%8C%E6%B6%88%E8%B4%B9%E8%80%85)

我不太明白暴露 callback 是什么意思？是指可以随时设置 callback 吗？

**Comment by MisterChing** [comment]
> @ggdream 生产者已经独立出来了。 [分开部署生产者和消费者](https://github.com/HDT3213/delayqueue/blob/master/README_CN.md#%E5%88%86%E5%BC%80%E9%83%A8%E7%BD%B2%E7%94%9F%E4%BA%A7%E8%80%85%E5%92%8C%E6%B6%88%E8%B4%B9%E8%80%85)
> 
> 我不太明白暴露 callback 是什么意思？是指可以随时设置 callback 吗？

嗯，目前处理函数只能在启动的时候注册进去，希望能在配置实例对象时注册

**Comment by ggdream** [comment]
@HDT3213 好的，辛苦

**Comment by HDT3213** [comment]
@MisterChing 忘记说了，队列阻塞监控也有了， [监控](https://github.com/HDT3213/delayqueue/blob/master/README_CN.md#%E8%8E%B7%E5%BE%97%E7%8A%B6%E6%80%81%E4%BF%A1%E6%81%AF)

```go
monitor := delayqueue.NewMonitor("example", redisCli)
blocked, err := monitor.GetReadyCount()
```

**Comment by MisterChing** [comment]
> @MisterChing 忘记说了，队列阻塞监控也有了， [监控](https://github.com/HDT3213/delayqueue/blob/master/README_CN.md#%E8%8E%B7%E5%BE%97%E7%8A%B6%E6%80%81%E4%BF%A1%E6%81%AF)
> 
> ```go
> monitor := delayqueue.NewMonitor("example", redisCli)
> blocked, err := monitor.GetReadyCount()
> ```

赞，辛苦
