### ISSUE TITLE
 consume error: pending2ReadyScript failed: ERR bad lua script for redis cluster, first parameter of redis.call/redis.pcall must be a single literal string

### ISSUE THREAD

**Issue by jimersylee** [HDT3213/delayqueue#12]
## 各个版本
- github.com/redis/go-redis/v9 v9.4.0
- github.com/hdt3213/delayqueue v1.0.4
- Redis: 阿里云集群版 Redis 6.0 | 集群版（16G，共2分片） | 云原生

## 使用方式
初始化时使用了UseHashTagKey()
delayQueue := delayqueue.NewQueue(queueName, RedisInstance, consumer, delayqueue.UseHashTagKey()).WithConcurrent(concurrent)

**Comment by HDT3213** [comment]
阿里云集群版 Redis 的 lua 脚本里 redis.call 第一个参数必须是字符串字面量， 我看看有什么办法绕过去

**Comment by HDT3213** [comment]
最新的 master 分支(461d5a1)上已经修复了，更新一下试试：

go get -u github.com/hdt3213/delayqueue@master

**Comment by HDT3213** [comment]
@jimersylee helllo, 现在能正常使用了吗？

**Comment by jimersylee** [comment]
可以了, 谢谢您🙏  ♥️&☮️
